### ISSUE TITLE
[Feature Request] No Chat Reports mod safe server status

### ISSUE THREAD

**Issue by MIOGMIOG** [e-im/FreedomChat#11]
Hello, can you make to display server with FreedomChat as safe server, when using No Chat Reports mod? (Also is it possible to create bungeecord plugin, which shows this too?)
[https://github.com/Aizistral-Studios/No-Chat-Reports/wiki/How-to-Get-Safe-Server-Status](https://github.com/Aizistral-Studios/No-Chat-Reports/wiki/How-to-Get-Safe-Server-Status#add-query-data)

**Comment by soshimee** [comment]
I will see if I can make a PR for it.

**Comment by soshimee** [comment]
I feel like a separate plugin for this actually.

**Comment by MIOGMIOG** [comment]
Has anyone done this yet?

**Comment by Frerduro** [comment]
+1 vote to have this integration added.

**Comment by e-im** [comment]
Sorry for not leaving a response for quite a while. I'll plan on adding this in a few days. It'll be behind a toggle, though, and likely default to off.

The rationale behind that is that many users of this plugin, including myself, do support chat reporting as a concept but are using this as a stopgap measure while they work to implement support for it in their own plugins, or due to concerns of false reports. This plugin is meant to be as simple and lean as possible. This is also why enforce-secure-profiles isn't reflectively disabled/etc. all this does is disable chat reporting server-side.

Hope that makes sense, although I'm open to other opinions.

**Comment by e-im** [comment]
I've added this. Note that it is disabled by default (`send-enforces-secure-chat-to-client` in `config.yml`) and will only work on Paper servers. Spigot/CraftBukkit are not supported, as I didn't really want to go hiking to get each channel earlier. on paper it is exposed.
