### ISSUE TITLE
[Feature Request] Add team color and prefix/suffix to chat messages 

### ISSUE THREAD

**Issue by KTech3020** [e-im/FreedomChat#26]
Currently all messages that is sent by FreedomChat does not showthe player's team color and/or prefix/suffixes like vanilla behaviour (see below) . Would it be possible to implement this?

Vanilla:
![image](https://user-images.githubusercontent.com/98096970/227106355-9fb2d12c-01ce-4645-a8b2-b8a145b1c7e3.png)
Server: (all plugins installed is shown; CowshedMP is a small plugin my server member made that only adds content and does not mess with chat in any way)
![image](https://user-images.githubusercontent.com/98096970/227106452-97dd97dc-a093-4d80-b36c-ad7249ebe568.png)

**Comment by e-im** [comment]
Unfortunately I can not look at the cause of this for a few days. However, I think there is a chance it is not caused by freedomchat.

CraftBukkit (and by extension Paper) disables coloring players names by their team by default. You have to explicitly enable this by setting [`use-vanilla-scoreboard-name-coloring`](https://docs.papermc.io/paper/reference/world-configuration#use-vanilla-world-scoreboard-name-coloring) to `true` in the paper world config. This is disabled by default because it conflicts with Bukkits display name API.

Let me know if this works.

**Comment by KTech3020** [comment]
It worked, thank you for the fast response!
