### ISSUE TITLE
No colors in console.

### ISSUE THREAD

**Issue by dkbay** [e-im/FreedomChat#7]
It seems that after I've started using this colors on chat messages in console are gone.

![image](https://user-images.githubusercontent.com/1548975/183600030-27062137-c48e-4fe5-a745-14b9e1a1867c.png)

It used to look like this instead before:
![image](https://user-images.githubusercontent.com/1548975/183600221-db37b154-29be-41bf-a74b-06e33d4dbae5.png)

**Comment by NDTurtle** [comment]
Same thing happens to me. Gradient colors and regular colors used to show up in console, but don't after installing freedomchat.

**Comment by Oharass** [comment]
Thank you for the report... I will work on this. It is more complex issue than it seems... I am not sure how quick for the fix.

**Comment by e-im** [comment]
Did you update your server/change anything else? Or just install FreedomChat?

Specifically in that screenshot you sent, more HAS to be different because just adding freedomchat will not add the `[Not Secure]` logging.

I've been unable to replicate this and don't obviously see what would be causing it. it'd likely be a conflict with another plugin, which can almost certainly be fixed if that is the case.

**Comment by Strahilchu** [comment]
I don't have this issue on standalone paper nor on velocity but will keep an eye out

**Comment by e-im** [comment]
I'm going to close this as cannot repro. If you are still experiencing this, please provide your whole plugin list - including highlighting which is providing coloured chat.
